name: Monitoramento do Pi-hole

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos
  workflow_dispatch:       # Permite execu√ß√£o manual

jobs:
  monitor-dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do c√≥digo
      uses: actions/checkout@v3

    - name: Instalar depend√™ncias
      run: sudo apt-get update && sudo apt-get install -y python3

    - name: Executar script de monitoramento DNS
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        ZONE_NAME: ${{ secrets.ZONE_NAME }}
        RECORD_NAME: ${{ secrets.RECORD_NAME }}
        IP_PIHOLE: ${{ secrets.IP_PIHOLE }}
        IP_BACKUP: ${{ secrets.IP_BACKUP }}

    - name: Teste vari√°vel CF_API_TOKEN
      run: echo "Token presente? ${CF_API_TOKEN:+Sim üëç / N√£o ‚ùå}"
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}


      run: python3 script-apitoken-cloudflare.py

